sudo: required
services:
- docker
env:
  global:
    # Ensure the downloaded SDK is first on the PATH
    - PATH=${HOME}/google-cloud-sdk/bin:$PATH
    # Ensure the install happens without prompts
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
language: node_js
node_js:
- '6'
before_install:
- npm install
install:
- docker build -t cloudboost/dashboard-ui:2.0.$TRAVIS_BUILD_NUMBER .
- docker build -t cloudboost/dashboard-ui:latest .
after_success:
#Deploy.
#Docker Login
- docker login --username $DOCKERUSERNAME --password $DOCKERPASSWORD --email $DOCKEREMAIL
#Push docker images.
- docker push cloudboost/dashboard-ui:2.0.$TRAVIS_BUILD_NUMBER
- docker push cloudboost/dashboard-ui:latest
# Make sure SDK is downloaded - cache once it's working
- curl https://sdk.cloud.google.com | bash;
# List the SDK contents to ensure it's downloaded
- ls -l ${HOME}/google-cloud-sdk/bin
# Ensure the correct gcloud is being used
- which gcloud
# Print the gcloud version and make sure it's something
- gcloud --version
- ls
#Activate Google Cloud SDK with your project
#- gcloud auth activate-service-account --key-file gc_cred.json
#Install Kubectl
- gcloud components install kubectl
- gcloud container clusters get-credentials $GOOGLECLUSTERNAME --zone $GOOGLEZONE --project $GOOGLEPROJECT
#Upload to Kubernetes for deployment.
- kubectl rolling-update cloudboost-dashboard-ui --image=cloudboost/dashboard-ui:latest --image-pull-policy=Always
